name: hmac_drgb
description: dart implementation of [HMAC DRBG]. dart implementation of [HMAC DRBG].
version: 2.0.0
homepage: https://github.com/Timu5/hmac_drgb

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  hash: ^1.0.4

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.21.1
